# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3_9hW9RqZx7etMcJN3WnFNIQDOVvN9E
"""

calif=[]
def leer (calif):
  for i in range(10):
    calif.append(float(input("dame tu calificación")))
def imprimir (calif):
  for i in calif:
    if (i>8.5):
      print(i)
  return (print)
leer (calif)
print(imprimir(calif))